remove extra ls and print repos
isbm/berrymill pull request #39
Opened 2023-10-31 17:54 UTC by osab270844

remove extra ls and print repos.

2023-10-31 19:59 UTC, isbm requested changes

2023-10-31 19:59 UTC, isbm commented on src/berry_mill/kiwrap.py
>          print(self._repos)
That too.

2023-11-02 09:43 UTC, osab270844 commented on src/berry_mill/kiwrap.py
>          print(self._repos)
Done.

2023-11-02 10:42 UTC, isbm approved these changes

2023-11-02 10:43 UTC, merged